name: Train Model

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Validate Data"]
    types:
      - completed

jobs:
  run_script:
    runs-on: macos-latest  # Use macOS runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: update-data

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow_scripts/tf_requirements.txt
          echo "TF_USE_LEGACY_KERAS=True" >> $GITHUB_ENV


      - name: "Start Train"
        run: |
          python workflow_scripts/get_rec_model.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          DATE=$(date +"%Y-%m-%d")
          git add .
          git commit -m "Update Recommender Model by GitHub Actions on $DATE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_SECRET }}
