name: Update Data

on:
  workflow_dispatch:
  repository_dispatch:
    types: [run_update_data]

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Reset update-data branch with main
        run: |
          BRANCH_NAME="update-data"  
          git checkout $BRANCH_NAME
          git reset --hard origin/main
    
      - name: Push new branch to the remote
        run: |
          # Push the reset branch, forcefully overwriting remote update-data
          git push --force --set-upstream origin update-data

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workflow_scripts/requirements.txt
          export TF_USE_LEGACY_KERAS=True

        # Run scripts
      - name: "Run script: Get buffs/debuffs"
        run: |
          python workflow_scripts/get_buffs_debuffs.py
      - name: "Run script: Get character ids"
        run: |
          python workflow_scripts/get_character_ids.py
      - name: "Run script: Get hero descriptions"
        run: |
          python workflow_scripts/get_hero_description.py
      - name: "Run script: Get hero official stats"
        run: |
          python workflow_scripts/get_hero_official_stats.py
      - name: "Run script: Calculate hero stats"
        run: |
          python workflow_scripts/get_hero_stats.py
      - name: "Run script: Get hero types"
        run: |
          python workflow_scripts/get_hero_types.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          DATE=$(date +"%Y-%m-%d")
          git add .
          git commit -m "Update Data by GitHub Actions on $DATE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_SECRET }}
